"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "hi" | "mr" | "pa" | "kn";

export interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  languages: { code: Language; label: string; native: string; flag: string }[];
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    app_title: "AI Smart Farming : AgriMind",
    app_badge: "BBDITM (Code: 054) • Team B8 • 2026-2027",
    app_subtitle: "Transforming Agriculture with AI-Powered Decision Support Systems",
    app_quote: "AI should support the farmer, not replace the farmer.",
    nav_overview: "Overview",
    nav_crop_rec: "Crop Recommend",
    nav_yield: "Yield Predict",
    nav_disease: "Disease Scan",
    nav_weather: "Weather Smart",
    nav_assistant: "AI Assistant",
    nav_integrated: "AgriMind in Action",
    emergency_call: "Kisan Call Center: 1800-180-1551",

    // Hero & Flow
    hero_pill: "Decision Support System for Modern Agriculture",
    hero_headline: "Smart Decisions for Every Stage of Your Crop",
    hero_desc: "From seed selection to harvest forecasting, leaf disease scanning, and weather alerts — AgriMind empowers farmers with precision AI guidance.",
    action_scan: "Scan Leaf for Disease",
    action_recommend: "Find Best Crop",
    action_demo: "See AgriMind In Action",

    // Feature 1
    f1_title: "Feature 1: AI Crop Recommendation",
    f1_sub: "Which crop is best suited for your specific field conditions?",
    f1_input_heading: "1. Farmer Inputs",
    f1_input_desc: "Soil type, Season, Water level & Location",
    f1_soil_type: "Soil Type",
    f1_season: "Season",
    f1_water_level: "Water / Irrigation Status",
    f1_location: "State / Region",
    f1_btn_analyze: "Analyze & Recommend Crops",
    f1_output_heading: "3. Suitable Crops",
    f1_output_desc: "AI compares field data with agricultural models to find optimal matches",
    f1_benefit_title: "Farmer Benefit",
    f1_benefit_desc: "Prevents crop failure by picking ideal soil matches, maximizes profit and resource utilization.",
    f1_easy_exp: "Easy Explanation: Instead of guessing what to plant, the farmer enters simple field details into the system. The AI compares these details with agricultural data and recommends the top crops that will grow best in that field.",

    // Feature 2
    f2_title: "Feature 2: ML Crop Yield Prediction",
    f2_sub: "How much harvest output can a farmer realistically expect?",
    f2_field_size: "Total Field Size (Hectares)",
    f2_seed_density: "Seed Density",
    f2_crop_select: "Selected Crop",
    f2_rain_prob: "Rain Probability (%)",
    f2_soil_quality: "Soil Health Index",
    f2_btn_predict: "Calculate Expected Harvest",
    f2_output_title: "Estimated Yield",
    f2_important_note: "Important Note: This calculation is a data-backed estimation, not a guaranteed promise. It assists farmers in storage planning, loan application, and market budgeting in advance.",
    f2_easy_exp: "Easy Explanation: Machine Learning learns from years of past farming data. By looking at crop type, field size, and weather forecasts, it provides a reliable estimate of harvest volume so farmers can plan ahead.",

    // Feature 3
    f3_title: "Feature 3: AI Plant Disease Detection",
    f3_sub: "Detect leaf symptoms early before damage spreads across the farm.",
    f3_step1: "1. Click / Upload Leaf Photo",
    f3_step1_desc: "Farmer snaps a clear image of infected leaf using smartphone camera or gallery.",
    f3_step2: "2. AI Computer Vision Scan",
    f3_step2_desc: "Image recognition compares spot patterns with multi-disease dataset.",
    f3_step3: "3. Issue Identification & Remedy",
    f3_step3_desc: "Shows possible issue, severity rating, and recommends consulting local expert.",
    f3_upload_cta: "Drag & drop or tap to take a photo of plant leaf",
    f3_sample_cta: "Or click a sample leaf photo to test instantly:",
    f3_btn_scan: "Run AI Vision Scan",
    f3_scanning: "Scanning leaf image with Convolutional Vision AI...",
    f3_easy_exp: "Easy Explanation: When a farmer notices yellow spots or marks on a plant leaf, they simply take a photo. The AI identifies the likely disease within seconds so the farmer can take quick corrective action.",

    // Feature 4
    f4_title: "Feature 4: Weather-Based Smart Farming",
    f4_sub: "Timely weather insights to prevent costly mistakes in daily farm activities.",
    f4_stream_title: "Live Weather Stream",
    f4_alert_engine: "Smart Alert Engine",
    f4_actionable_notification: "Actionable Notification",
    f4_spraying_title: "Spraying Decisions",
    f4_spraying_desc: "Prevents chemical runoff when unexpected rain is expected.",
    f4_irrigation_title: "Irrigation Management",
    f4_irrigation_desc: "Saves water and electricity if rain is predicted naturally.",
    f4_harvesting_title: "Sowing & Harvesting",
    f4_harvesting_desc: "Helps pick dry windows for heavy field equipment work.",
    f4_easy_exp: "Easy Explanation: Weather can ruin pesticides or waste irrigation water. AgriMind sends clear, plain-language alerts like 'Rain expected tomorrow – delay spraying today' to save time and money.",

    // Feature 5
    f5_title: "Feature 5: AI Farming Assistant",
    f5_sub: "Instant answers to everyday farming questions in simple regional language.",
    f5_assistant_name: "AgriMind Voice & Text Assistant",
    f5_natural_input: "Natural Input: Type or speak naturally without technical jargon.",
    f5_multi_topic: "Multi-Topic: Seasons, fertilizer dosages, soil care & government schemes.",
    f5_safety_first: "Safety First: For severe outbreaks, directs farmer to official agricultural experts.",
    f5_input_placeholder: "Ask anything about crops, soil, pest spray, schemes...",
    f5_btn_send: "Send",
    f5_btn_listen: "Speak",
    f5_easy_exp: "Easy Explanation: Like a 24/7 digital farming guide, farmers can ask questions anytime by voice or typing, getting quick and practical answers regarding crops, weather, and soil health.",

    // Ecosystem & Real Example
    eco_title: "Integrated System: All 5 Features",
    eco_sub: "A single connected ecosystem guiding the entire crop cycle from start to finish.",
    eco_banner: "Integrated Farmer Journey: Raw Field Data → AI Insights → Confident Decisions",
    real_example_title: "Real Example: AgriMind in Action",
    real_example_sub: "How a real farmer uses AgriMind to make smart choices during Kharif season.",
    real_insight: "Key Insight: AgriMind gives actionable guidance, but the farmer always makes the final decision using their local wisdom and expert consultations.",

    // Benefits & Conclusion
    benefits_title: "Key Benefits for Farmers",
    benefit_1_title: "1. Simple & Easy",
    benefit_1_desc: "Replaces complex agricultural research data with simple, clean recommendations that anyone can understand without technical training.",
    benefit_2_title: "2. Timely Alerts",
    benefit_2_desc: "Weather warnings and disease scans reach the farmer proactively, right before critical farming activities take place.",
    benefit_3_title: "3. Personalized Advice",
    benefit_3_desc: "Guidance is customized strictly around the farmer's specific field location, soil type, and current weather context.",
    benefit_4_title: "4. Practical All-in-One",
    benefit_4_desc: "Combines 5 essential smart farming tools into one simple platform, removing the need for multiple apps.",
    conclusion_title: "Conclusion: Empowering Farmers",
    loop_step1: "1. Field Data",
    loop_step2: "2. AI Processing",
    loop_step3: "3. Farmer Decision",
    loop_outcome: "Better Information → Better Decisions → Smarter Farming",
  },
  hi: {
    app_title: "एआई स्मार्ट फार्मिंग : एग्रीमाइंड",
    app_badge: "BBDITM (कोड: 054) • टीम B8 • 2026-2027",
    app_subtitle: "एआई-संचालित निर्णय प्रणाली के साथ भारतीय कृषि का सशक्तिकरण",
    app_quote: "एआई को किसान की सहायता करनी चाहिए, किसान की जगह नहीं लेनी चाहिए।",
    nav_overview: "सिंहावलोकन",
    nav_crop_rec: "फसल सुझाव",
    nav_yield: "उपज अनुमान",
    nav_disease: "पत्ती रोग जांच",
    nav_weather: "मौसम अलर्ट",
    nav_assistant: "एआई सहायक",
    nav_integrated: "एग्रीमाइंड डेमो",
    emergency_call: "किसान कॉल सेंटर: 1800-180-1551",

    hero_pill: "आधुनिक खेती के लिए एआई निर्णय सहायता प्रणाली",
    hero_headline: "फसल के हर चरण में सही व समय पर निर्णय",
    hero_desc: "बीज चयन से लेकर फसल उपज अनुमान, पत्ती रोग पहचान और मौसम अलर्ट तक — एग्रीमाइंड हर किसान को सटीक दिशा दिखाता है।",
    action_scan: "पत्ती का रोग पहचानें",
    action_recommend: "उपयुक्त फसल जानें",
    action_demo: "एग्रीमाइंड इन एक्शन देखें",

    f1_title: "सुविधा 1: एआई फसल सिफारिश (Crop Recommendation)",
    f1_sub: "आपके खेत की मिट्टी और मौसम के लिए कौन सी फसल सबसे लाभदायक है?",
    f1_input_heading: "1. किसान की जानकारी",
    f1_input_desc: "मिट्टी का प्रकार, मौसम, सिंचाई की सुविधा व स्थान",
    f1_soil_type: "मिट्टी का प्रकार",
    f1_season: "ऋतु / मौसम",
    f1_water_level: "सिंचाई व पानी की स्थिति",
    f1_location: "राज्य / क्षेत्र",
    f1_btn_analyze: "खेत जांचें और फसल चुनें",
    f1_output_heading: "3. सर्वोत्तम अनुशंसित फसलें",
    f1_output_desc: "एआई मॉडल ने खेत के पोषक तत्वों व मौसम के आधार पर उपयुक्त फसलें चुनी हैं",
    f1_benefit_title: "किसान को लाभ",
    f1_benefit_desc: "गलत फसल चुनने का जोखिम खत्म, कम लागत में अधिकतम उत्पादन व मुनाफा।",
    f1_easy_exp: "सरल भाषा में: बिना किसी उलझन के किसान अपने खेत की आसान जानकारी डालते हैं। एआई कृषि डेटा से तुलना करके बताता है कि कौन सी फसल सबसे अच्छी पैदावार देगी।",

    f2_title: "सुविधा 2: एमएल फसल उपज अनुमान (Yield Prediction)",
    f2_sub: "किसान अपनी मेहनत से कितनी उपज की वास्तविक उम्मीद रख सकता है?",
    f2_field_size: "खेत का कुल क्षेत्रफल (हेक्टेयर)",
    f2_seed_density: "बीज घनत्व",
    f2_crop_select: "बोई जाने वाली फसल",
    f2_rain_prob: "बारिश की संभावना (%)",
    f2_soil_quality: "मिट्टी गुणवत्ता सूचकांक",
    f2_btn_predict: "संभावित पैदावार का हिसाब लगाएं",
    f2_output_title: "अनुमानित कुल पैदावार",
    f2_important_note: "महत्वपूर्ण नोट: यह गणना ऐतिहासिक डेटा पर आधारित अनुमान है। यह किसानों को भंडारण, मंडी व्यवस्था और कृषि ऋण की योजना बनाने में मदद करती है।",
    f2_easy_exp: "सरल भाषा में: मशीन लर्निंग पिछले कई वर्षों के फसल डेटा, खेत के आकार और मौसम के आधार पर पैदावार का सटीक अनुमान देती है।",

    f3_title: "सुविधा 3: एआई पादप रोग पहचान (Plant Disease Detection)",
    f3_sub: "बीमारी पूरे खेत में फैलने से पहले पत्ती के लक्षणों की पहचान करें।",
    f3_step1: "1. पत्ती की फोटो लें / अपलोड करें",
    f3_step1_desc: "मोबाइल कैमरे से प्रभावित पत्ती की साफ तस्वीर लें।",
    f3_step2: "2. एआई कंप्यूटर विजन स्कैन",
    f3_step2_desc: "धब्बों और पैटर्न की तुलना फसल रोग डेटाबेस से की जाती है।",
    f3_step3: "3. रोग की पहचान व उपचार",
    f3_step3_desc: "संभावित रोग, गंभीरता व जैविक/रासायनिक उपचार का तुरंत सुझाव।",
    f3_upload_cta: "पत्ती की फोटो यहां खींचें या अपलोड करें",
    f3_sample_cta: "या तुरंत टेस्ट करने के लिए सैंपल पत्ती चुनें:",
    f3_btn_scan: "एआई स्कैन शुरू करें",
    f3_scanning: "कंप्यूटर विजन मॉडल पत्ती के धब्बों की जांच कर रहा है...",
    f3_easy_exp: "सरल भाषा में: पत्ती पर पीलापन या धब्बा दिखते ही फोटो खींचें। एआई तुरंत बीमारी पहचान कर सही दवा और घरेलू उपाय बता देगा।",

    f4_title: "सुविधा 4: मौसम-आधारित स्मार्ट खेती (Weather Farming)",
    f4_sub: "समय पर मौसम की जानकारी से दैनिक कृषि कार्यों में नुकसान से बचें।",
    f4_stream_title: "लाइव मौसम पूर्वानुमान",
    f4_alert_engine: "स्मार्ट अलर्ट इंजन",
    f4_actionable_notification: "उपयोगी किसान सलाह",
    f4_spraying_title: "कीटनाशक छिड़काव निर्णय",
    f4_spraying_desc: "अचानक बारिश से दवा बहने का नुकसान रोकता है।",
    f4_irrigation_title: "सिंचाई प्रबंधन",
    f4_irrigation_desc: "प्राकृतिक बारिश के पूर्वानुमान से पानी व बिजली की बचत।",
    f4_harvesting_title: "बुवाई व कटाई विंडो",
    f4_harvesting_desc: "ट्रैक्टर व भारी मशीनरी के लिए सूखे दिनों की सटीक जानकारी।",
    f4_easy_exp: "सरल भाषा में: बारिश से दवा धुलने और पानी बर्बाद होने से बचाने के लिए एआई समय रहते सलाह देता है: 'कल बारिश की संभावना है, आज छिड़काव न करें।' ",

    f5_title: "सुविधा 5: एआई कृषि सहायक (AI Farming Assistant)",
    f5_sub: "अपनी भाषा में खेती के हर सवाल का तुरंत सही समाधान पाएं।",
    f5_assistant_name: "एग्रीमाइंड वॉइस व टेक्स्ट सहायक",
    f5_natural_input: "स्वाभाविक इनपुट: बिना किसी तकनीकी उलझन के बोलें या लिखें।",
    f5_multi_topic: "विविध ज्ञान: फसल चक्र, खाद मात्रा, मिट्टी देखभाल और सरकारी योजनाएं।",
    f5_safety_first: "सुरक्षा प्राथमिकता: गंभीर बीमारी की स्थिति में नजदीकी कृषि वैज्ञानिक से संपर्क कराता है।",
    f5_input_placeholder: "फसल, खाद, मौसम या सरकारी योजनाओं के बारे में पूछें...",
    f5_btn_send: "पूछें",
    f5_btn_listen: "बोलें",
    f5_easy_exp: "सरल भाषा में: 24/7 डिजिटल कृषि सलाहकार की तरह किसान बोलकर या लिखकर कभी भी अपनी भाषा में सही सलाह ले सकते हैं।",

    eco_title: "एकीकृत प्रणाली: सभी 5 सुविधाएं (Integrated Ecosystem)",
    eco_sub: "फसल के पहले दिन से अंतिम दिन तक किसान का संपूर्ण मार्गदर्शन।",
    eco_banner: "किसान यात्रा: खेत का कच्चा डेटा → एआई विश्लेषण → आत्मविश्वास भरा सही निर्णय",
    real_example_title: "वास्तविक उदाहरण: एग्रीमाइंड इन एक्शन",
    real_example_sub: "खरीफ मौसम में एक किसान कैसे एग्रीमाइंड से सही फैसले लेता है।",
    real_insight: "मुख्य सीख: एग्रीमाइंड सटीक सलाह देता है, परंतु अंतिम निर्णय सदैव किसान के अपने अनुभव व विवेक का होता है।",

    benefits_title: "किसानों के लिए मुख्य लाभ",
    benefit_1_title: "1. सरल व सुगम",
    benefit_1_desc: "बिना किसी तकनीकी ज्ञान के कोई भी किसान आसानी से समझ सकता है।",
    benefit_2_title: "2. समय पर अलर्ट",
    benefit_2_desc: "जरूरी कृषि कार्य करने से ठीक पहले चेतावनी किसान तक पहुंचती है।",
    benefit_3_title: "3. व्यक्तिगत सलाह",
    benefit_3_desc: "आपके खेत, आपकी मिट्टी और स्थानीय मौसम के अनुसार विशिष्ट मार्गदर्शन।",
    benefit_4_title: "4. संपूर्ण ऑल-इन-वन",
    benefit_4_desc: "अलग-अलग ऐप की जरूरत नहीं, खेती के 5 जरूरी समाधान एक ही जगह।",
    conclusion_title: "निष्कर्ष: किसान का सशक्तिकरण",
    loop_step1: "1. खेत का डेटा",
    loop_step2: "2. एआई विश्लेषण",
    loop_step3: "3. किसान का निर्णय",
    loop_outcome: "बेहतर जानकारी → बेहतर निर्णय → उन्नत व समृद्ध खेती",
  },
  mr: {
    app_title: "एआय स्मार्ट शेती : ॲग्रीमाइंड (AgriMind)",
    app_badge: "BBDITM (कोड: 054) • टीम B8 • 2026-2027",
    app_subtitle: "एआय आधारित निर्णय प्रणालीने शेतीचा विकास",
    app_quote: "एआयने शेतकऱ्याला साथ दिली पाहिजे, त्याची जागा घेऊ नये.",
    nav_overview: "माहिती",
    nav_crop_rec: "पीक शिफारस",
    nav_yield: "उत्पादन अंदाज",
    nav_disease: "रोग निदान",
    nav_weather: "हवामान अलर्ट",
    nav_assistant: "एआय सहाय्यक",
    nav_integrated: "ॲग्रीमाइंड डेमो",
    emergency_call: "किसान कॉल सेंटर: 1800-180-1551",

    hero_pill: "शेतकऱ्यांसाठी आधुनिक एआय निर्णय प्रणाली",
    hero_headline: "बियाण्यापासून काढणीपर्यंत योग्य निर्णय",
    hero_desc: "माती परीक्षण, पीक शिफारस, रोग निदान आणि हवामान अलर्ट — ॲग्रीमाइंड शेतकऱ्यांना अचूक मार्गदर्शन करते.",
    action_scan: "पानावरील रोग तपासा",
    action_recommend: "योग्य पीक निवडा",
    action_demo: "ॲग्रीमाइंड डेमो पहा",

    f1_title: "वैशिष्ट्य 1: एआय पीक शिफारस (Crop Recommendation)",
    f1_sub: "तुमच्या शेतातील माती आणि पाण्यासाठी कोणते पीक सर्वोत्तम आहे?",
    f1_input_heading: "1. शेतकऱ्याची माहिती",
    f1_input_desc: "मातीचा प्रकार, हंगाम, पाण्याची सोय आणि स्थान",
    f1_soil_type: "मातीचा प्रकार",
    f1_season: "हंगाम",
    f1_water_level: "पाण्याची उपलब्धता",
    f1_location: "राज्य / विभाग",
    f1_btn_analyze: "माती तपासा व पीक निवडा",
    f1_output_heading: "3. योग्य पिके",
    f1_output_desc: "एआयने शेताच्या घटकांवरून सर्वोत्तम पिके निवडली आहेत",
    f1_benefit_title: "शेतकऱ्याचा फायदा",
    f1_benefit_desc: "चुकीच्या पिकाची लागवड टळते, जास्तीत जास्त नफा मिळतो.",
    f1_easy_exp: "सोप्या शब्दात: अंदाजाने लागवड करण्याऐवजी शेताची माहिती द्या, एआय सांगेल की सर्वात जास्त फायदा कशात होईल.",

    f2_title: "वैशिष्ट्य 2: एमएल पीक उत्पादन अंदाज (Yield Prediction)",
    f2_sub: "या हंगामात शेतकऱ्याला प्रत्यक्ष किती उत्पन्न मिळू शकेल?",
    f2_field_size: "शेताचे क्षेत्रफळ (हेक्टर)",
    f2_seed_density: "बियाणे प्रमाण",
    f2_crop_select: "निवडलेले पीक",
    f2_rain_prob: "पावसाची शक्यता (%)",
    f2_soil_quality: "माती आरोग्य निर्देशांक",
    f2_btn_predict: "उत्पादनाचा अंदाज काढा",
    f2_output_title: "अपेक्षित एकूण उत्पादन",
    f2_important_note: "महत्त्वाची नोंद: हा अंदाज पूर्वानुभवावर आधारित आहे. साठवणूक आणि कर्ज नियोजनासाठी याचा उपयोग होतो.",
    f2_easy_exp: "सोप्या शब्दात: मशीन लर्निंग आधीच्या डेटा आणि हवामानाच्या आधारे उत्पन्नाचा अचूक अंदाज देते.",

    f3_title: "वैशिष्ट्य 3: एआय वनस्पती रोग निदान (Disease Detection)",
    f3_sub: "रोग पसरण्यापूर्वीच पानांच्या लक्षणांवरून त्वरित ओळख करा.",
    f3_step1: "1. पानाचा फोटो काढा / अपलोड करा",
    f3_step1_desc: "मोबाईल कॅमेऱ्याने बाधित पानाचा फोटो घ्या.",
    f3_step2: "2. एआय कॉम्प्युटर व्हिजन स्कॅन",
    f3_step2_desc: "डागांची तुलना रोग डेटाबेसशी केली जाते.",
    f3_step3: "3. रोग ओळख आणि उपाय",
    f3_step3_desc: "रोगाचे नाव, तीव्रता आणि उपाय लगेच दाखवले जातात.",
    f3_upload_cta: "पानाचा फोटो येथे अपलोड करा",
    f3_sample_cta: "किंवा तपासण्यासाठी नमुना पान निवडा:",
    f3_btn_scan: "एआय स्कॅन करा",
    f3_scanning: "व्हिजन मॉडेल पानावरील रोगाची तपासणी करत आहे...",
    f3_easy_exp: "सोप्या शब्दात: पानावरील डाग दिसताच फोटो काढा, एआय काही सेकंदात आजार ओळखून उपाय सांगेल.",

    f4_title: "वैशिष्ट्य 4: हवामानावर आधारित स्मार्ट शेती (Weather Smart)",
    f4_sub: "वेळेवर हवामान माहिती मिळवून रोजच्या कामात नुकसान टाळा.",
    f4_stream_title: "थेट हवामान अंदाज",
    f4_alert_engine: "स्मार्ट अलर्ट इंजिन",
    f4_actionable_notification: "शेतकऱ्यांसाठी कृती सूचना",
    f4_spraying_title: "फवारणी निर्णय",
    f4_spraying_desc: "पावसामुळे औषध वाहून जाणे रोखले जाते.",
    f4_irrigation_title: "पाणी व्यवस्थापन",
    f4_irrigation_desc: "नैसर्गिक पावसामुळे पाणी आणि वीज वाचते.",
    f4_harvesting_title: "काढणी व मशागत",
    f4_harvesting_desc: "यंत्रसामग्रीसाठी कोरड्या दिवसांची माहिती मिळते.",
    f4_easy_exp: "सोप्या शब्दात: पावसात फवारणी वाया जाऊ नये म्हणून अलर्ट येतो: 'उद्या पाऊस आहे, आज फवारणी थांबवा.'",

    f5_title: "वैशिष्ट्य 5: एआय शेती सहाय्यक (AI Assistant)",
    f5_sub: "आपल्या भाषेत शेतीच्या प्रत्येक प्रश्नाचे उत्तर मिळवा.",
    f5_assistant_name: "ॲग्रीमाइंड व्हॉइस व टेक्स्ट सहाय्यक",
    f5_natural_input: "नैसर्गिक संवाद: कोणत्याही तांत्रिक भाषेविना बोला किंवा लिहा.",
    f5_multi_topic: "विविध विषय: खतांचे प्रमाण, पीक हंगाम आणि सरकारी योजना.",
    f5_safety_first: "सुरक्षा प्रथम: गंभीर समस्येवर थेट कृषी तज्ञांकडे मार्गदर्शन.",
    f5_input_placeholder: "पिके, खते, रोग किंवा योजनांबद्दल विचारा...",
    f5_btn_send: "विचारा",
    f5_btn_listen: "बोला",
    f5_easy_exp: "सोप्या शब्दात: २४ तास उपलब्ध मित्र जो शेतकऱ्यांच्या सर्व प्रश्नांची मराठीत उत्तरे देतो.",

    eco_title: "सर्व ५ वैशिष्ट्ये एकत्रित (Integrated Ecosystem)",
    eco_sub: "पीक नियोजनापासून काढणीपर्यंत संपूर्ण शेती मार्गदर्शन.",
    eco_banner: "शेतकरी प्रवास: शेताची माहिती → एआय विश्लेषण → अचूक निर्णय",
    real_example_title: "प्रत्यक्ष उदाहरण: ॲग्रीमाइंड कृतीमध्ये",
    real_example_sub: "खरीप हंगामात शेतकरी कसा स्मार्ट निर्णय घेतो.",
    real_insight: "महत्त्वाची गोष्ट: ॲग्रीमाइंड सल्ला देते, परंतु अंतिम निर्णय नेहमी शेतकऱ्याचाच असतो.",

    benefits_title: "शेतकऱ्यांसाठी प्रमुख फायदे",
    benefit_1_title: "1. सोपे आणि सुलभ",
    benefit_1_desc: "कोणत्याही तांत्रिक ज्ञानाशिवाय सहज समजणारे मार्गदर्शन.",
    benefit_2_title: "2. वेळेवर अलर्ट",
    benefit_2_desc: "महत्त्वाच्या कामापूर्वीच हवामान आणि रोगाचे अलर्ट मिळतात.",
    benefit_3_title: "3. वैयक्तिक सल्ला",
    benefit_3_desc: "तुमच्या शेतानुसार आणि मातीनुसार थेट उपाय.",
    benefit_4_title: "4. सर्व काही एकाच ठिकाणी",
    benefit_4_desc: "५ स्मार्ट टूल्स एकाच सोप्या ॲपमध्ये उपलब्ध.",
    conclusion_title: "निष्कर्ष: शेतकऱ्यांचे सक्षमीकरण",
    loop_step1: "1. शेताचा डेटा",
    loop_step2: "2. एआय प्रक्रिया",
    loop_step3: "3. शेतकऱ्याचा निर्णय",
    loop_outcome: "चांगली माहिती → योग्य निर्णय → प्रगत शेती",
  },
  pa: {
    app_title: "ਏਆਈ ਸਮਾਰਟ ਫਾਰਮਿੰਗ : ਐਗਰੀਮਾਈਂਡ (AgriMind)",
    app_badge: "BBDITM (ਕੋਡ: 054) • ਟੀਮ B8 • 2026-2027",
    app_subtitle: "ਏਆਈ ਤਕਨੀਕ ਨਾਲ ਕਿਸਾਨਾਂ ਲਈ ਸਮਾਰਟ ਫੈਸਲੇ",
    app_quote: "ਏਆਈ ਨੂੰ ਕਿਸਾਨ ਦੀ ਮਦਦ ਕਰਨੀ ਚਾਹੀਦੀ ਹੈ, ਕਿਸਾਨ ਦੀ ਥਾਂ ਨਹੀਂ ਲੈਣੀ ਚਾਹੀਦੀ।",
    nav_overview: "ਸੰਖੇਪ",
    nav_crop_rec: "ਫਸਲ ਸਿਫਾਰਸ਼",
    nav_yield: "ਝਾੜ ਅਨੁਮਾਨ",
    nav_disease: "ਪੱਤਾ ਰੋਗ ਜਾਂਚ",
    nav_weather: "ਮੌਸਮ ਅਲਰਟ",
    nav_assistant: "ਏਆਈ ਸਹਾਇਕ",
    nav_integrated: "ਐਗਰੀਮਾਈਂਡ ਡੈਮੋ",
    emergency_call: "ਕਿਸਾਨ ਕਾਲ ਸੈਂਟਰ: 1800-180-1551",

    hero_pill: "ਕਿਸਾਨਾਂ ਲਈ ਆਧੁਨਿਕ ਏਆਈ ਫੈਸਲਾ ਪ੍ਰਣਾਲੀ",
    hero_headline: "ਬੀਜ ਬੀਜਣ ਤੋਂ ਲੈ ਕੇ ਵਾਢੀ ਤੱਕ ਸਹੀ ਫੈਸਲਾ",
    hero_desc: "ਮਿੱਟੀ ਪਰਖ, ਫਸਲ ਚੋਣ, ਪੱਤਾ ਰੋਗ ਪਛਾਣ ਅਤੇ ਮੌਸਮ ਅਲਰਟ — ਐਗਰੀਮਾਈਂਡ ਨਾਲ ਹਰ ਕਿਸਾਨ ਲਵੇ ਸਹੀ ਫੈਸਲਾ।",
    action_scan: "ਪੱਤੇ ਦਾ ਰੋਗ ਜਾਂਚੋ",
    action_recommend: "ਢੁਕਵੀਂ ਫਸਲ ਚੁਣੋ",
    action_demo: "ਐਗਰੀਮਾਈਂਡ ਡੈਮੋ ਵੇਖੋ",

    f1_title: "ਵਿਸ਼ੇਸ਼ਤਾ 1: ਏਆਈ ਫਸਲ ਸਿਫਾਰਸ਼ (Crop Recommendation)",
    f1_sub: "ਤੁਹਾਡੇ ਖੇਤ ਦੀ ਮਿੱਟੀ ਅਤੇ ਮੌਸਮ ਲਈ ਕਿਹੜੀ ਫਸਲ ਸਭ ਤੋਂ ਵਧੀਆ ਹੈ?",
    f1_input_heading: "1. ਕਿਸਾਨ ਵੱਲੋਂ ਜਾਣਕਾਰੀ",
    f1_input_desc: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ, ਮੌਸਮ, ਪਾਣੀ ਦੀ ਸਹੂਲਤ ਅਤੇ ਇਲਾਕਾ",
    f1_soil_type: "ਮਿੱਟੀ ਦੀ ਕਿਸਮ",
    f1_season: "ਮੌਸਮ / ਸੀਜ਼ਨ",
    f1_water_level: "ਸਿੰਚਾਈ ਦੀ ਸਹੂਲਤ",
    f1_location: "ਸੂਬਾ / ਜ਼ਿਲ੍ਹਾ",
    f1_btn_analyze: "ਖੇਤ ਦੀ ਜਾਂਚ ਕਰੋ ਤੇ ਫਸਲ ਚੁਣੋ",
    f1_output_heading: "3. ਢੁਕਵੀਆਂ ਫਸਲਾਂ",
    f1_output_desc: "ਏਆਈ ਨੇ ਮਿੱਟੀ ਦੇ ਤੱਤਾਂ ਅਨੁਸਾਰ ਸਭ ਤੋਂ ਵਧੀਆ ਫਸਲਾਂ ਚੁਣੀਆਂ ਹਨ",
    f1_benefit_title: "ਕਿਸਾਨ ਨੂੰ ਫਾਇਦਾ",
    f1_benefit_desc: "ਗਲਤ ਫਸਲ ਬੀਜਣ ਦਾ ਨੁਕਸਾਨ ਬਚਦਾ ਹੈ ਅਤੇ ਵੱਧ ਮੁਨਾਫਾ ਮਿਲਦਾ ਹੈ।",
    f1_easy_exp: "ਸੌਖੇ ਸ਼ਬਦਾਂ ਵਿੱਚ: ਅੰਦਾਜ਼ਾ ਲਗਾਉਣ ਦੀ ਥਾਂ ਖੇਤ ਦੀ ਜਾਣਕਾਰੀ ਭਰੋ, ਏਆਈ ਦੱਸੇਗਾ ਕਿ ਕਿਹੜੀ ਫਸਲ ਸਭ ਤੋਂ ਵੱਧ ਕਮਾਈ ਦੇਵੇਗੀ।",

    f2_title: "ਵਿਸ਼ੇਸ਼ਤਾ 2: ਐਮਐਲ ਫਸਲ ਝਾੜ ਅਨੁਮਾਨ (Yield Prediction)",
    f2_sub: "ਇਸ ਸੀਜ਼ਨ ਵਿੱਚ ਕਿਸਾਨ ਨੂੰ ਕਿੰਨਾ ਝਾੜ ਮਿਲਣ ਦੀ ਉਮੀਦ ਹੈ?",
    f2_field_size: "ਖੇਤ ਦਾ ਰਕਬਾ (ਹੈਕਟੇਅਰ)",
    f2_seed_density: "ਬੀਜ ਦੀ ਮਾਤਰਾ",
    f2_crop_select: "ਚੁਣੀ ਹੋਈ ਫਸਲ",
    f2_rain_prob: "ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ (%)",
    f2_soil_quality: "ਮਿੱਟੀ ਸਿਹਤ ਇੰਡੈਕਸ",
    f2_btn_predict: "ਸੰਭਾਵਿਤ ਝਾੜ ਦਾ ਹਿਸਾਬ ਲਗਾਓ",
    f2_output_title: "ਅਨੁਮਾਨਿਤ ਕੁੱਲ ਝਾੜ",
    f2_important_note: "ਜ਼ਰੂਰੀ ਨੋਟ: ਇਹ ਪਿਛਲੇ ਡਾਟੇ ਦੇ ਆਧਾਰ ਤੇ ਅਨੁਮਾਨ ਹੈ। ਇਹ ਮੰਡੀਕਰਨ ਅਤੇ ਖਰਚਿਆਂ ਦੀ ਯੋਜਨਾ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।",
    f2_easy_exp: "ਸੌਖੇ ਸ਼ਬਦਾਂ ਵਿੱਚ: ਮਸ਼ੀਨ ਲਰਨਿੰਗ ਪਿਛਲੇ ਸਾਲਾਂ ਦੇ ਰਿਕਾਰਡ ਤੋਂ ਸਹੀ ਝਾੜ ਦਾ ਅੰਦਾਜ਼ਾ ਲਗਾਉਂਦੀ ਹੈ।",

    f3_title: "ਵਿਸ਼ੇਸ਼ਤਾ 3: ਏਆਈ ਪੌਦਾ ਰੋਗ ਪਛਾਣ (Disease Detection)",
    f3_sub: "ਰੋਗ ਫੈਲਣ ਤੋਂ ਪਹਿਲਾਂ ਹੀ ਪੱਤਿਆਂ ਦੇ ਲੱਛਣ ਪਛਾਣੋ।",
    f3_step1: "1. ਪੱਤੇ ਦੀ ਫੋਟੋ ਲਵੋ / ਅਪਲੋਡ ਕਰੋ",
    f3_step1_desc: "ਮੋਬਾਈਲ ਕੈਮਰੇ ਨਾਲ ਬਿਮਾਰ ਪੱਤੇ ਦੀ ਸਾਫ ਫੋਟੋ ਲਵੋ।",
    f3_step2: "2. ਏਆਈ ਕੰਪਿਊਟਰ ਵਿਜ਼ਨ ਸਕੈਨ",
    f3_step2_desc: "ਦਾਗਾਂ ਅਤੇ ਪੈਟਰਨਾਂ ਦੀ ਜਾਂਚ ਰੋਗ ਡਾਟਾਬੇਸ ਨਾਲ ਹੁੰਦੀ ਹੈ।",
    f3_step3: "3. ਰੋਗ ਦੀ ਪਛਾਣ ਤੇ ਇਲਾਜ",
    f3_step3_desc: "ਰੋਗ ਦਾ ਨਾਂ, ਗੰਭੀਰਤਾ ਅਤੇ ਦੇਸੀ ਤੇ ਰਸਾਇਣਕ ਇਲਾਜ ਤੁਰੰਤ ਮਿਲਦਾ ਹੈ।",
    f3_upload_cta: "ਪੱਤੇ ਦੀ ਫੋਟੋ ਇੱਥੇ ਅਪਲੋਡ ਕਰੋ",
    f3_sample_cta: "ਜਾਂ ਟੈਸਟ ਕਰਨ ਲਈ ਨਮੂਨਾ ਪੱਤਾ ਚੁਣੋ:",
    f3_btn_scan: "ਏਆਈ ਸਕੈਨ ਸ਼ੁਰੂ ਕਰੋ",
    f3_scanning: "ਏਆਈ ਪੱਤੇ ਦੀ ਜਾਂਚ ਕਰ ਰਿਹਾ ਹੈ...",
    f3_easy_exp: "ਸੌਖੇ ਸ਼ਬਦਾਂ ਵਿੱਚ: ਪੱਤੇ ਤੇ ਪੀਲਾਪਨ ਜਾਂ ਦਾਗ ਦਿਖਦੇ ਹੀ ਫੋਟੋ ਖਿੱਚੋ, ਏਆਈ ਤੁਰੰਤ ਬਿਮਾਰੀ ਅਤੇ ਸਹੀ ਦਵਾਈ ਦੱਸੇਗਾ।",

    f4_title: "ਵਿਸ਼ੇਸ਼ਤਾ 4: ਮੌਸਮ ਆਧਾਰਿਤ ਸਮਾਰਟ ਖੇਤੀ (Weather Smart)",
    f4_sub: "ਸਮੇਂ ਸਿਰ ਮੌਸਮ ਜਾਣਕਾਰੀ ਨਾਲ ਖੇਤੀ ਖਰਚਿਆਂ ਤੋਂ ਬਚੋ।",
    f4_stream_title: "ਲਾਈਵ ਮੌਸਮ ਜਾਣਕਾਰੀ",
    f4_alert_engine: "ਸਮਾਰਟ ਅਲਰਟ ਇੰਜਣ",
    f4_actionable_notification: "ਜ਼ਰੂਰੀ ਕਿਸਾਨ ਸਲਾਹ",
    f4_spraying_title: "ਸਪਰੇਅ ਕਰਨ ਦਾ ਫੈਸਲਾ",
    f4_spraying_desc: "ਮੀਂਹ ਕਾਰਨ ਦਵਾਈ ਵਹਿਣ ਦਾ ਨੁਕਸਾਨ ਰੋਕਦਾ ਹੈ।",
    f4_irrigation_title: "ਪਾਣੀ ਪ੍ਰਬੰਧਨ",
    f4_irrigation_desc: "ਕੁਦਰਤੀ ਮੀਂਹ ਦੀ ਸੰਭਾਵਨਾ ਕਾਰਨ ਬਿਜਲੀ ਅਤੇ ਪਾਣੀ ਬਚਾਉਂਦਾ ਹੈ।",
    f4_harvesting_title: "ਵਾਢੀ ਅਤੇ ਬਿਜਾਈ",
    f4_harvesting_desc: "ਟਰੈਕਟਰ ਅਤੇ ਮਸ਼ੀਨਾਂ ਲਈ ਸੁੱਕੇ ਦਿਨਾਂ ਦੀ ਜਾਣਕਾਰੀ ਦਿੰਦਾ ਹੈ।",
    f4_easy_exp: "ਸੌਖੇ ਸ਼ਬਦਾਂ ਵਿੱਚ: ਮੀਂਹ ਨਾਲ ਸਪਰੇਅ ਖਰਾਬ ਨਾ ਹੋਵੇ, ਐਗਰੀਮਾਈਂਡ ਸੁਨੇਹਾ ਭੇਜਦਾ ਹੈ: 'ਕੱਲ੍ਹ ਮੀਂਹ ਹੈ, ਅੱਜ ਸਪਰੇਅ ਨਾ ਕਰੋ।' ",

    f5_title: "ਵਿਸ਼ੇਸ਼ਤਾ 5: ਏਆਈ ਖੇਤੀਬਾੜੀ ਸਹਾਇਕ (AI Assistant)",
    f5_sub: "ਆਪਣੀ ਬੋਲੀ ਵਿੱਚ ਖੇਤੀ ਦੇ ਸਾਰੇ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਲਵੋ।",
    f5_assistant_name: "ਐਗਰੀਮਾਈਂਡ ਆਵਾਜ਼ ਅਤੇ ਲਿਖਤ ਸਹਾਇਕ",
    f5_natural_input: "ਕੁਦਰਤੀ ਗੱਲਬਾਤ: ਬਿਨਾਂ ਔਖੇ ਸ਼ਬਦਾਂ ਦੇ ਬੋਲੋ ਜਾਂ ਲਿਖੋ।",
    f5_multi_topic: "ਸਾਰੇ ਵਿਸ਼ੇ: ਖਾਦ ਦੀ ਮਾਤਰਾ, ਕੀੜੇ-ਮਕੌੜੇ ਅਤੇ ਸਰਕਾਰੀ ਸਕੀਮਾਂ।",
    f5_safety_first: "ਸੁਰੱਖਿਆ ਪਹਿਲਾਂ: ਵੱਡੀ ਸਮੱਸਿਆ ਹੋਣ ਤੇ ਖੇਤੀ ਮਾਹਿਰਾਂ ਨਾਲ ਸੰਪਰਕ ਕਰਵਾਉਂਦਾ ਹੈ।",
    f5_input_placeholder: "ਫਸਲਾਂ, ਖਾਦ, ਮੌਸਮ ਜਾਂ ਸਕੀਮਾਂ ਬਾਰੇ ਪੁੱਛੋ...",
    f5_btn_send: "ਪੁੱਛੋ",
    f5_btn_listen: "ਬੋਲੋ",
    f5_easy_exp: "ਸੌਖੇ ਸ਼ਬਦਾਂ ਵਿੱਚ: 24 ਘੰਟੇ ਸਾਥੀ ਜੋ ਕਿਸਾਨਾਂ ਦੇ ਹਰ ਸਵਾਲ ਦਾ ਪੰਜਾਬੀ ਵਿੱਚ ਜਵਾਬ ਦਿੰਦਾ ਹੈ।",

    eco_title: "ਸਾਰੇ 5 ਫੀਚਰ ਇਕੱਠੇ (Integrated Ecosystem)",
    eco_sub: "ਫਸਲ ਬੀਜਣ ਤੋਂ ਕੱਟਣ ਤੱਕ ਪੂਰੀ ਅਗਵਾਈ।",
    eco_banner: "ਕਿਸਾਨ ਦਾ ਸਫਰ: ਖੇਤ ਦਾ ਡਾਟਾ → ਏਆਈ ਸੋਚ → ਭਰੋਸੇਮੰਦ ਫੈਸਲਾ",
    real_example_title: "ਅਸਲ ਮਿਸਾਲ: ਐਗਰੀਮਾਈਂਡ ਕੰਮ ਕਰਦਾ ਹੋਇਆ",
    real_example_sub: "ਖਰੀਫ ਸੀਜ਼ਨ ਵਿੱਚ ਕਿਸਾਨ ਕਿਵੇਂ ਸਮਾਰਟ ਫੈਸਲੇ ਲੈਂਦਾ ਹੈ।",
    real_insight: "ਅਹਿਮ ਨੁਕਤਾ: ਐਗਰੀਮਾਈਂਡ ਸਲਾਹ ਦਿੰਦਾ ਹੈ, ਪਰ ਆਖਰੀ ਫੈਸਲਾ ਹਮੇਸ਼ਾ ਕਿਸਾਨ ਦਾ ਆਪਣਾ ਹੁੰਦਾ ਹੈ।",

    benefits_title: "ਕਿਸਾਨਾਂ ਲਈ ਮੁੱਖ ਫਾਇਦੇ",
    benefit_1_title: "1. ਬਿਲਕੁਲ ਸਰਲ",
    benefit_1_desc: "ਬਿਨਾਂ ਕਿਸੇ ਤਕਨੀਕੀ ਮੁਹਾਰਤ ਦੇ ਆਸਾਨੀ ਨਾਲ ਸਮਝ ਆਉਣ ਵਾਲੀ ਸਲਾਹ।",
    benefit_2_title: "2. ਵੇਲੇ ਸਿਰ ਅਲਰਟ",
    benefit_2_desc: "ਖੇਤੀ ਕੰਮ ਸ਼ੁਰੂ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਹੀ ਸੁਚੇਤ ਕਰਦਾ ਹੈ।",
    benefit_3_title: "3. ਨਿੱਜੀ ਮਾਰਗਦਰਸ਼ਨ",
    benefit_3_desc: "ਤੁਹਾਡੇ ਖੇਤ ਅਤੇ ਮਿੱਟੀ ਮੁਤਾਬਕ ਖਾਸ ਸਲਾਹ।",
    benefit_4_title: "4. ਸਭ ਕੁਝ ਇੱਕ ਥਾਂ",
    benefit_4_desc: "ਵੱਖ-ਵੱਖ ਐਪਾਂ ਦੀ ਲੋੜ ਨਹੀਂ, 5 ਜ਼ਰੂਰੀ ਟੂਲ ਇੱਕੋ ਪਲੇਟਫਾਰਮ ਤੇ।",
    conclusion_title: "ਨਤੀਜਾ: ਕਿਸਾਨ ਦਾ ਸਸ਼ਕਤੀਕਰਨ",
    loop_step1: "1. ਖੇਤ ਦਾ ਡਾਟਾ",
    loop_step2: "2. ਏਆਈ ਪ੍ਰੋਸੈਸਿੰਗ",
    loop_step3: "3. ਕਿਸਾਨ ਦਾ ਫੈਸਲਾ",
    loop_outcome: "ਬਿਹਤਰ ਜਾਣਕਾਰੀ → ਬਿਹਤਰ ਫੈਸਲੇ → ਖੁਸ਼ਹਾਲ ਖੇਤੀ",
  },
  kn: {
    app_title: "ಎಐ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ : ಅಗ್ರಿಮೈಂಡ್ (AgriMind)",
    app_badge: "BBDITM (ಕೋಡ್: 054) • ತಂಡ B8 • 2026-2027",
    app_subtitle: "ಎಐ ತಂತ್ರಜ್ಞಾನದೊಂದಿಗೆ ರೈತರಿಗೆ ನಿಖರ ನಿರ್ಧಾರ ಬೆಂಬಲ ವ್ಯವಸ್ಥೆ",
    app_quote: "ಎಐ ರೈತನಿಗೆ ಬೆಂಬಲ ನೀಡಬೇಕೇ ಹೊರತು ರೈತನ ಸ್ಥಾನವನ್ನು ಪಡೆಯಬಾರದು.",
    nav_overview: "ವಿವರಣೆ",
    nav_crop_rec: "ಬೆಳೆ ಶಿಫಾರಸು",
    nav_yield: "ಇಳುವರಿ ಅಂದಾಜು",
    nav_disease: "ಎಲೆ ರೋಗ ತಪಾಸಣೆ",
    nav_weather: "ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ",
    nav_assistant: "ಎಐ ಸಹಾಯಕ",
    nav_integrated: "ಅಗ್ರಿಮೈಂಡ್ ಡೆಮೊ",
    emergency_call: "ಕಿಸಾನ್ ಕಾಲ್ ಸೆಂಟರ್: 1800-180-1551",

    hero_pill: "ಆಧುನಿಕ ಕೃಷಿಗಾಗಿ ಎಐ ನಿರ್ಧಾರ ಬೆಂಬಲ ವ್ಯವಸ್ಥೆ",
    hero_headline: "ಬೆಳೆಯ ಪ್ರತಿಯೊಂದು ಹಂತದಲ್ಲೂ ನಿಖರ ನಿರ್ಧಾರ",
    hero_desc: "ಬೀಜ ಆಯ್ಕೆಯಿಂದ ಹಿಡಿದು ಇಳುವರಿ ಅಂದಾಜು, ಎಲೆ ರೋಗ ಪತ್ತೆ ಮತ್ತು ಹವಾಮಾನ ಎಚ್ಚರಿಕೆವರೆಗೆ — ಅಗ್ರಿಮೈಂಡ್ ರೈತನಿಗೆ ಸದಾ ಜತೆಯಾಗಿರುತ್ತದೆ.",
    action_scan: "ಎಲೆಯ ರೋಗ ತಪಾಸಿಸಿ",
    action_recommend: "ಸೂಕ್ತ ಬೆಳೆ ತಿಳಿಯಿರಿ",
    action_demo: "ಅಗ್ರಿಮೈಂಡ್ ಡೆಮೊ ನೋಡಿ",

    f1_title: "ವೈಶಿಷ್ಟ್ಯ 1: ಎಐ ಬೆಳೆ ಶಿಫಾರಸು (Crop Recommendation)",
    f1_sub: "ನಿಮ್ಮ ಜಮೀನಿನ ಮಣ್ಣು ಮತ್ತು ಹವಾಮಾನಕ್ಕೆ ಯಾವ ಬೆಳೆ ಅತ್ಯುತ್ತಮ?",
    f1_input_heading: "1. ರೈತರ ಮಾಹಿತಿ",
    f1_input_desc: "ಮಣ್ಣಿನ ವಿಧ, ಋತು, ನೀರಾವರಿ ಸ್ಥಿತಿ ಮತ್ತು ಸ್ಥಳ",
    f1_soil_type: "ಮಣ್ಣಿನ ವಿಧ",
    f1_season: "ಋತು / ಸೀಸನ್",
    f1_water_level: "ನೀರಾವರಿ ಸೌಲಭ್ಯ",
    f1_location: "ರಾಜ್ಯ / ಪ್ರದೇಶ",
    f1_btn_analyze: "ಮಣ್ಣು ತಪಾಸಿಸಿ ಬೆಳೆ ಆಯ್ಕೆ ಮಾಡಿ",
    f1_output_heading: "3. ಸೂಕ್ತವಾದ ಬೆಳೆಗಳು",
    f1_output_desc: "ಎಐ ಮಣ್ಣಿನ ಪೋಷಕಾಂಶಗಳ ಆಧಾರದ ಮೇಲೆ ಉತ್ತಮ ಬೆಳೆಗಳನ್ನು ಶಿಫಾರಸು ಮಾಡಿದೆ",
    f1_benefit_title: "ರೈತನಿಗೆ ಲಾಭ",
    f1_benefit_desc: "ತಪ್ಪು ಬೆಳೆ ಆಯ್ಕೆಯ ನಷ್ಟ ತಪ್ಪಿಸಿ, ಗರಿಷ್ಠ ಇಳುವರಿ ಮತ್ತು ಲಾಭ ನೀಡುತ್ತದೆ.",
    f1_easy_exp: "ಸರಳ ವಿವರಣೆ: ಅಂದಾಜಿನಲ್ಲಿ ಬಿತ್ತನೆ ಮಾಡುವ ಬದಲು ಹೊಲದ ವಿವರ ನೀಡಿ, ಎಐ ಅತಿ ಹೆಚ್ಚು ಇಳುವರಿ ಕೊಡುವ ಬೆಳೆಗಳನ್ನು ತಿಳಿಸುತ್ತದೆ.",

    f2_title: "ವೈಶಿಷ್ಟ್ಯ 2: ಎಂಎಲ್ ಬೆಳೆ ಇಳುವರಿ ಅಂದಾಜು (Yield Prediction)",
    f2_sub: "ಈ ಹಂಗಾಮಿನಲ್ಲಿ ರೈತ ಎಷ್ಟು ಇಳುವರಿ ನಿರೀಕ್ಷಿಸಬಹುದು?",
    f2_field_size: "ಜಮೀನಿನ ವಿಸ್ತೀರ್ಣ (ಹೆಕ್ಟೇರ್)",
    f2_seed_density: "ಬೀಜ ಸಾಂದ್ರತೆ",
    f2_crop_select: "ಆಯ್ಕೆ ಮಾಡಿದ ಬೆಳೆ",
    f2_rain_prob: "ಮಳೆಯ ಸಾಧ್ಯತೆ (%)",
    f2_soil_quality: "ಮಣ್ಣಿನ ಗುಣಮಟ್ಟ ಸೂಚ್ಯಂಕ",
    f2_btn_predict: "ಇಳುವರಿ ಅಂದಾಜು ಲೆಕ್ಕ ಹಾಕಿ",
    f2_output_title: "ಅಂದಾಜು ಒಟ್ಟು ಇಳುವರಿ",
    f2_important_note: "ಪ್ರಮುಖ ಸೂಚನೆ: ಇದು ಹಿಂದಿನ ದಾಖಲೆಗಳ ಆಧಾರಿತ ಅಂದಾಜು. ಮಾರುಕಟ್ಟೆ ಮತ್ತು ಸಾಲ ಯೋಜನೆಗೆ ಇದು ಸಹಕಾರಿಯಾಗಿದೆ.",
    f2_easy_exp: "ಸರಳ ವಿವರಣೆ: ಮೆಷಿನ್ ಲರ್ನಿಂಗ್ ಹಿಂದಿನ ವರ್ಷಗಳ ಕೃಷಿ ಮಾಹಿತಿ ಮತ್ತು ಹವಾಮಾನದ ಆಧಾರದ ಮೇಲೆ ನಿಖರ ಇಳುವರಿ ಅಂದಾಜು ನೀಡುತ್ತದೆ.",

    f3_title: "ವೈಶಿಷ್ಟ್ಯ 3: ಎಐ ಸಸ್ಯ ರೋಗ ಪತ್ತೆ (Plant Disease Detection)",
    f3_sub: "ರೋಗ ಹರಡುವ ಮುನ್ನವೇ ಎಲೆಯ ಲಕ್ಷಣಗಳಿಂದ ಶೀಘ್ರ ರೋಗ ಪತ್ತೆ ಮಾಡಿ.",
    f3_step1: "1. ಎಲೆಯ ಫೋಟೋ ತೆಗೆಯಿರಿ / ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    f3_step1_desc: "ಮೊಬೈಲ್ ಕ್ಯಾಮೆರಾದಿಂದ ಪೀಡಿತ ಎಲೆಯ ಸ್ಪಷ್ಟ ಚಿತ್ರ ತೆಗೆಯಿರಿ.",
    f3_step2: "2. ಎಐ ಕಂಪ್ಯೂಟರ್ ವಿಷನ್ ಸ್ಕ್ಯಾನ್",
    f3_step2_desc: "ಮಚ್ಚೆಗಳು ಮತ್ತು ರೋಗ ಲಕ್ಷಣಗಳನ್ನು ಡೇಟಾಬೇಸ್‌ನೊಂದಿಗೆ ಹೋಲಿಸಲಾಗುತ್ತದೆ.",
    f3_step3: "3. ರೋಗ ಗುರುತಿಸುವಿಕೆ ಮತ್ತು ಪರಿಹಾರ",
    f3_step3_desc: "ರೋಗದ ಹೆಸರು, ತೀವ್ರತೆ ಮತ್ತು ಸಾವಯವ ಹಾಗೂ ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆ ತಿಳಿಯುತ್ತದೆ.",
    f3_upload_cta: "ಎಲೆಯ ಚಿತ್ರವನ್ನು ಇಲ್ಲಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    f3_sample_cta: "ಅಥವಾ ತಕ್ಷಣ ಪರೀಕ್ಷಿಸಲು ಮಾದರಿ ಎಲೆ ಆಯ್ಕೆಮಾಡಿ:",
    f3_btn_scan: "ಎಐ ಸ್ಕ್ಯಾನ್ ಆರಂಭಿಸಿ",
    f3_scanning: "ಎಐ ಮಾದರಿಯು ಎಲೆಯ ರೋಗ ಲಕ್ಷಣಗಳನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡುತ್ತಿದೆ...",
    f3_easy_exp: "ಸರಳ ವಿವರಣೆ: ಎಲೆಯ ಮೇಲೆ ಹಳದಿ ಚುಕ್ಕೆ ಕಂಡ ಕೂಡಲೇ ಫೋಟೋ ತೆಗೆಯಿರಿ. ಎಐ ತಕ್ಷಣ ರೋಗ ಪತ್ತೆಹಚ್ಚಿ ಪರಿಹಾರ ಸೂಚಿಸುತ್ತದೆ.",

    f4_title: "ವೈಶಿಷ್ಟ್ಯ 4: ಹವಾಮಾನ ಆಧಾರಿತ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ (Weather Smart)",
    f4_sub: "ಸಮಯೋಚಿತ ಹವಾಮಾನ ಮಾಹಿತಿಯಿಂದ ದೈನಂದಿನ ಕೃಷಿ ನಷ್ಟ ತಪ್ಪಿಸಿ.",
    f4_stream_title: "ಲೈವ್ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ",
    f4_alert_engine: "ಸ್ಮಾರ್ಟ್ ಎಚ್ಚರಿಕೆ ಇಂಜಿನ್",
    f4_actionable_notification: "ರೈತರಿಗೆ ಕ್ರಿಯಾತ್ಮಕ ಸಲಹೆ",
    f4_spraying_title: "ಔಷಧ ಸಿಂಪಡಣೆ ನಿರ್ಧಾರ",
    f4_spraying_desc: "ಅನಿರೀಕ್ಷಿತ ಮಳೆಯಿಂದ ಔಷಧ ವ್ಯರ್ಥವಾಗುವುದನ್ನು ತಡೆಯುತ್ತದೆ.",
    f4_irrigation_title: "ನೀರಾವರಿ ನಿರ್ವಹಣೆ",
    f4_irrigation_desc: "ನೈಸರ್ಗಿಕ ಮಳೆಯ ಮುನ್ಸೂಚನೆಯಿಂದ ನೀರು ಮತ್ತು ವಿದ್ಯುತ್ ಉಳಿತಾಯ.",
    f4_harvesting_title: "ಬಿತ್ತನೆ ಮತ್ತು ಕೊಯ್ಲು",
    f4_harvesting_desc: "ಯಂತ್ರೋಪಕರಣಗಳ ಬಳಕೆಗೆ ಒಣ ಹವೆ ದಿನಗಳ ನಿಖರ ಮಾಹಿತಿ ನೀಡುತ್ತದೆ.",
    f4_easy_exp: "ಸರಳ ವಿವರಣೆ: ಮಳೆಯಿಂದ ಸಿಂಪಡಣೆ ಹಾಳಾಗುವುದನ್ನು ತಪ್ಪಿಸಲು ಎಚ್ಚರಿಕೆ ನೀಡುತ್ತದೆ: 'ನಾಳೆ ಮಳೆಯಾಗಲಿದೆ - ಇಂದು ಔಷಧ ಸಿಂಪಡಿಸಬೇಡಿ.'",

    f5_title: "ವೈಶಿಷ್ಟ್ಯ 5: ಎಐ ಕೃಷಿ ಸಹಾಯಕ (AI Assistant)",
    f5_sub: "ನಿಮ್ಮ ಮಾತೃಭಾಷೆಯಲ್ಲಿ ಕೃಷಿಯ ಎಲ್ಲಾ ಪ್ರಶ್ನೆಗಳಿಗೆ ತಕ್ಷಣ ಉತ್ತರ ಪಡೆಯಿರಿ.",
    f5_assistant_name: "ಅಗ್ರಿಮೈಂಡ್ ಧ್ವನಿ ಮತ್ತು ಬರಹ ಸಹಾಯಕ",
    f5_natural_input: "ಸಹಜ ಸಂವಹನ: ಕ್ಲಿಷ್ಟ ಪದಗಳಿಲ್ಲದೆ ಮಾತನಾಡಿ ಅಥವಾ ಬರೆಯಿರಿ.",
    f5_multi_topic: "ವಿವಿಧ ವಿಷಯಗಳು: ರಸಗೊಬ್ಬರ ಪ್ರಮಾಣ, ಬೆಳೆ ಕಾಲ ಮತ್ತು ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು.",
    f5_safety_first: "ಸುರಕ್ಷತೆ ಮೊದಲು: ಗಂಭೀರ ಸಮಸ್ಯೆಯಿದ್ದಲ್ಲಿ ಕೃಷಿ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಲು ಸೂಚಿಸುತ್ತದೆ.",
    f5_input_placeholder: "ಬೆಳೆ, ಗೊಬ್ಬರ, ಹವಾಮಾನ ಅಥವಾ ಯೋಜನೆಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    f5_btn_send: "ಕೇಳಿ",
    f5_btn_listen: "ಮಾತನಾಡಿ",
    f5_easy_exp: "ಸರಳ ವಿವರಣೆ: 24/7 ಲಭ್ಯವಿರುವ ಡಿಜಿಟಲ್ ಮಾರ್ಗದರ್ಶಿಯಂತೆ ರೈತರು ತಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಯಾವುದೇ ಪ್ರಶ್ನೆಗೆ ಉತ್ತರ ಪಡೆಯಬಹುದು.",

    eco_title: "ಎಲ್ಲಾ 5 ವೈಶಿಷ್ಟ್ಯಗಳ ಸಮಗ್ರ ವ್ಯವಸ್ಥೆ (Integrated Ecosystem)",
    eco_sub: "ಬೆಳೆ ಬಿತ್ತನೆಯಿಂದ ಕಟಾವಿನವರೆಗೆ ರೈತನಿಗೆ ಸಂಪೂರ್ಣ ಮಾರ್ಗದರ್ಶನ.",
    eco_banner: "ರೈತರ ಪಯಣ: ಹೊಲದ ಮಾಹಿತಿ → ಎಐ ವಿಶ್ಲೇಷಣೆ → ವಿಶ್ವಾಸಾರ್ಹ ನಿರ್ಧಾರ",
    real_example_title: "ನೈಜ ಉದಾಹರಣೆ: ಅಗ್ರಿಮೈಂಡ್ ಕಾರ್ಯಾಚರಣೆ",
    real_example_sub: "ಖಾರೀಫ್ ಹಂಗಾಮಿನಲ್ಲಿ ರೈತ ಹೇಗೆ ಚತುರ ನಿರ್ಧಾರಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತಾನೆ.",
    real_insight: "ಪ್ರಮುಖ ಅಂಶ: ಅಗ್ರಿಮೈಂಡ್ ನಿಖರ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತದೆ, ಆದರೆ ಅಂತಿಮ ನಿರ್ಧಾರ ಯಾವಾಗಲೂ ರೈತನ ಅನುಭವದ್ದೇ ಆಗಿರುತ್ತದೆ.",

    benefits_title: "ರೈತರಿಗೆ ಪ್ರಮುಖ ಪ್ರಯೋಜನಗಳು",
    benefit_1_title: "1. ಸರಳ ಮತ್ತು ಸುಲಭ",
    benefit_1_desc: "ಯಾವುದೇ ತಾಂತ್ರಿಕ ತರಬೇತಿಯಿಲ್ಲದೆ ಯಾರು ಬೇಕಾದರೂ ಸುಲಭವಾಗಿ ಅರ್ಥಮಾಡಿಕೊಳ್ಳಬಹುದು.",
    benefit_2_title: "2. ಸಮಯೋಚಿತ ಎಚ್ಚರಿಕೆ",
    benefit_2_desc: "ಕೃಷಿ ಕಾರ್ಯಗಳನ್ನು ಪ್ರಾರಂಭಿಸುವ ಮೊದಲೇ ಹವಾಮಾನ ಮತ್ತು ರೋಗ ಎಚ್ಚರಿಕೆ ತಲುಪುತ್ತದೆ.",
    benefit_3_title: "3. ವೈಯಕ್ತಿಕ ಸಲಹೆ",
    benefit_3_desc: "ನಿಮ್ಮ ಜಮೀನು, ಮಣ್ಣು ಮತ್ತು ಹವಾಮಾನಕ್ಕೆ ಸೂಕ್ತವಾದ ನಿಖರ ಮಾರ್ಗದರ್ಶನ.",
    benefit_4_title: "4. ಆಲ್-ಇನ್-ಒನ್ ವ್ಯವಸ್ಥೆ",
    benefit_4_desc: "ಬೇರೆ ಬೇರೆ ಆ್ಯಪ್‌ಗಳ ಅಗತ್ಯವಿಲ್ಲ, 5 ಪ್ರಮುಖ ಕೃಷಿ ಪರಿಕರಗಳು ಒಂದೇ ವೇದಿಕೆಯಲ್ಲಿವೆ.",
    conclusion_title: "ತೀರ್ಮಾನ: ರೈತರ ಸಬಲೀಕರಣ",
    loop_step1: "1. ಹೊಲದ ಮಾಹಿತಿ",
    loop_step2: "2. ಎಐ ಸಂಸ್ಕರಣೆ",
    loop_step3: "3. ರೈತರ ನಿರ್ಧಾರ",
    loop_outcome: "ಉತ್ತಮ ಮಾಹಿತಿ → ಉತ್ತಮ ನಿರ್ಧಾರಗಳು → ಸಮೃದ್ಧ ಕೃಷಿ",
  },
};

export const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
  languages: [],
});

export const availableLanguages: { code: Language; label: string; native: string; flag: string }[] = [
  { code: "en", label: "English", native: "English", flag: "🇬🇧" },
  { code: "hi", label: "Hindi", native: "हिंदी", flag: "🇮🇳" },
  { code: "mr", label: "Marathi", native: "मराठी", flag: "🚩" },
  { code: "pa", label: "Punjabi", native: "ਪੰਜਾਬੀ", flag: "🌾" },
  { code: "kn", label: "Kannada", native: "ಕನ್ನಡ", flag: "🟡" },
];

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("agrimind_lang") as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("agrimind_lang", lang);
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations["en"]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languages: availableLanguages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
